### ISSUE TITLE
Implement Linked Lists

### ISSUE THREAD

**Issue by ankitjena** [zairza-cetb/hacktoberfest-2018#17]
* Should have basic operations of linked list, can be singly or doubly linked list
* Can be in any language, multiple submissions from single language are not welcome
* Solutions should be submitted to this [directory](https://github.com/zairza-cetb/hacktoberfest-2018/tree/master/data_structures/linked_lists)
* Make a subfolder of the language name in the solution directory

**Comment by Delkhaz** [comment]
I’ll tackle c++ implementation !

**Comment by megamayoy** [comment]
I would like to add circularly linked list in C++
