### ISSUE TITLE
Implement insertion sort

### ISSUE THREAD

**Issue by Kirty-Goyal** [zairza-cetb/hacktoberfest-2018#55]
* To learn about insertion sort, refer this [link](https://www.geeksforgeeks.org/insertion-sort/)
* You are allowed to implement the algorithm in any language.
* Multiple submissions from a single language are not allowed.
* Solutions are to be submitted in this  [directory](https://github.com/zairza-cetb/hacktoberfest-2018/tree/master/sort/insertion_sort) .
* To make a submission in python. You have to create a sub-folder python inside insertion_sort and save your file in it.
> insertion_sort/python/insertion_sort.py

**Comment by MansiNegi27** [comment]
Can I work on implementing this in Java and JavaScript?
