### ISSUE TITLE
implement Merge Sort

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/hacktoberfest-2018#7]
- You are allowed to implement the algorithm in any language.
- Multiple submissions from a single language are not allowed.
- Solutions are to be submitted in this [directory](https://github.com/zairza-cetb/hacktoberfest-2018/tree/master/sort/merge_sort).
- To make a submission in python. You have to create a sub-folder python inside merge_sort and save your file in it.

**Comment by alloro** [comment]
I'll add the one for golang

**Comment by megamayoy** [comment]
I will add merge sort algorithm in C++

**Comment by drdraad** [comment]
I'll implement the Python version of #7

**Comment by mishramonalisha76** [comment]
I am interested to work on this issue.

**Comment by rajashree23** [comment]
I'll  implement the code in C language.

**Comment by becomingadarsha** [comment]
I will implement in **Javascript**.

**Comment by ankitjena** [comment]
@becomingadarsha We are not accepting pull requests in the repo
